# -*- coding: utf-8 -*-
"""Stock Ticker Dashboard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r-en_Hsmzzl-WCKowjA5ah-lFOQ0ClOA

https://colab.research.google.com/

https://www.nasdaq.com/market-activity/stocks/screener
"""

from google.colab import files

files.upload()

import pandas

dataframe = pandas.read_csv("Nasdaq.csv")

print(dataframe)

dataframe.head()

dataframe.info()

dataframe.describe()

!pip install jupyter-dash
!pip install dash

from jupyter_dash import JupyterDash

import dash

import dash_html_components as html

app = JupyterDash(__name__)

app.layout = html.Div([
                       html.H1("Stock Ticker Web App")
])

app.run_server(port = 3030)